const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_API_KEY,
});

// ✅ ZOD SCHEMA (MATCH WITH MONGOOSE)
const interviewReportSchema = z.object({
  title: z.string(),
  matchScore: z.number(),

  technicalQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    }),
  ),

  behavioralQuestions: z.array(
    z.object({
      question: z.string(),
      intention: z.string(),
      answer: z.string(),
    }),
  ),

  skillGaps: z.array(
    z.object({
      skill: z.string(),
      severity: z.enum(["low", "medium", "high"]),
    }),
  ),

  preparationRecommendations: z.array(
    z.object({
      day: z.number(),
      focus: z.string(),
      task: z.string(),
    }),
  ),
});

// ✅ Retry (for rate limit)
async function generateWithRetry(fn, retries = 2) {
  try {
    return await fn();
  } catch (err) {
    if (err.status === 429 && retries > 0) {
      console.log("Retrying...");
      await new Promise((res) => setTimeout(res, 30000));
      return generateWithRetry(fn, retries - 1);
    }
    throw err;
  }
}

// ✅ MAIN FUNCTION
async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `
You are an expert interviewer.

Return ONLY valid JSON.

STRICT FORMAT:

{
  "title": "string",
  "matchScore": number,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answer": "string"
    }
  ],
  "skillGaps": [
    {
      "skill": "string",
      "severity": "low | medium | high"
    }
  ],
  "preparationRecommendations": [
    {
      "day": number,
      "focus": "string",
      "task": "string"
    }
  ]
}

RULES:
- "title" should be a short job-role based heading
- DO NOT return strings inside arrays
- DO NOT stringify objects
- ALL arrays must contain OBJECTS
- minimum:
  - 3 technicalQuestions
  - 3 behavioralQuestions
  - 3 skillGaps
  - 5 preparationRecommendations

DATA:
Resume: ${resume.slice(0, 1000)}
Self Description: ${selfDescription}
Job Description: ${jobDescription}
`;

  const response = await generateWithRetry(() =>
    ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [{ text: prompt }],
        },
      ],
      config: {
        temperature: 0.2,
      },
    }),
  );

  // ✅ FIX: correct text extraction
  let text =
    response?.candidates?.[0]?.content?.parts?.[0]?.text || response.text;

  // 🔥 REMOVE ```json ... ``` wrapper
  text = text.trim();

  if (text.startsWith("```")) {
    text = text
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();
  }

  console.log("RAW AI RESPONSE:", text);

  let parsed;

  try {
    parsed = JSON.parse(text);
  } catch (err) {
    throw new Error("AI returned invalid JSON");
  }

  // ✅ VALIDATE WITH ZOD (VERY IMPORTANT)
  const validated = interviewReportSchema.safeParse(parsed);

  if (!validated.success) {
    console.error(validated.error);
    throw new Error("AI response format incorrect");
  }

  return validated.data;
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });
  const pdfBuffer = await page.pdf({ format: "A4", margins: { top: "20mm", bottom: "20mm", left: "15mm", right: "15mm" } });
  await browser.close();
  return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumePdfSchema = z.object({
    html: z.string().describe("the HTML content for the resume PDF"), // base64 PDF string
  });

  const prompt = `Generate a resume for a candidate with the following details:
  
  Resume: ${resume.slice(0, 1000)}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}

  the response should be a JSON object with a single field "html" containing the HTML content for the resume PDF.
  the resume shoubld be ATS-friendly, well-formatted, and tailored to the job description. Use the self description to add a personal touch to the resume. Return ONLY the JSON object with the "html" field, no explanations or extra text.
  the content should be not sound like generated by AI, but a real resume created by a human. Use common resume sections like Summary, Skills, Experience, Education etc. and populate them based on the input data.
  and resume should be concise, ideally fitting into 1 pages when converted to PDF.
  you can highlight relevant skills and experience that match the job description, and use the self description to add a unique personal summary at the top. Remember, the output MUST be a JSON object with an "html" field containing the HTML string for the resume. NO markdown, NO explanations, ONLY JSON.
  but the content like simple and straightforward language, avoid buzzwords and cliches, and make it look like a genuine resume created by a real person. DO NOT include any AI-related phrases or disclaimers in the content. The HTML should be clean and simple, suitable for conversion to PDF without formatting issues.
  
  `;

  const response = await generateWithRetry(() =>
    ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [
        {
          role: "user",
          parts: [{ text: prompt }],
        },
      ],
      config: {
        responseMimeType: "application/json",
        responseSchema: zodToJsonSchema(resumePdfSchema),
        temperature: 0.2,
      },
    }),
  );

  const jsonContent = JSON.parse(response.text);

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);

  return pdfBuffer;
}

module.exports = {
  generateInterviewReport,
  generateResumePdf,
  generatePdfFromHtml
};
